# Generated by Django 6.0 on 2025-12-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_colors',
            field=models.ManyToManyField(blank=True, to='catalog.product', verbose_name='Варианты (другие цвета)'),
        ),
    ]
