# Generated by Django 6.0 on 2025-12-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_related_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Главный Hero'), ('brand', 'Блок Бренда'), ('banner', 'Баннер')], default='brand', max_length=20),
        ),
    ]
