# Generated by Django 6.0 on 2025-12-27 22:32

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Generate slugs for existing brands"""
    Brand = apps.get_model('catalog', 'Brand')
    for brand in Brand.objects.all():
        if not brand.slug:
            brand.slug = slugify(brand.name)
            # Ensure uniqueness
            original_slug = brand.slug
            counter = 1
            while Brand.objects.filter(slug=brand.slug).exclude(pk=brand.pk).exists():
                brand.slug = f"{original_slug}-{counter}"
                counter += 1
            brand.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='brands/banners/', verbose_name='Баннер'),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, default=''),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
