# Generated by Django 6.0 on 2025-12-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_brand_banner_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image_url',
            field=models.URLField(blank=True, help_text='Или укажите URL изображения вместо загрузки файла', max_length=500, verbose_name='Главное фото (ссылка)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Или укажите URL изображения вместо загрузки файла', max_length=500, verbose_name='Фото (ссылка)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Главное фото (файл)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='Фото (файл)'),
        ),
    ]
