# Generated by Django 6.0 on 2025-12-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_main_image_url_productimage_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=120, verbose_name='Артикул'),
        ),
    ]
