# Generated by ChatGPT on 2026-01-16
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_product_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='promo_is_active',
            field=models.BooleanField(default=False, verbose_name='Показывать промо-модалку'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_image',
            field=models.ImageField(blank=True, null=True, upload_to='promo/', verbose_name='Изображение промо'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка при клике'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_eyebrow',
            field=models.CharField(blank=True, max_length=120, verbose_name='Надпись над заголовком'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
