# Generated by ChatGPT on 2026-01-16
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_sitesettings_promo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='new_logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/new/', verbose_name='Логотип (новый)'),
        ),
    ]
