# Generated by Django 6.0 on 2026-01-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.TextField(blank=True, help_text='Текст будет отображаться под размерами в сером облаке', verbose_name='Примечание (облако)'),
        ),
    ]
