# Generated by Django 6.0 on 2026-01-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_product_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='color',
            field=models.CharField(default='#a71930', help_text='HEX-код цвета (например, #a71930)', max_length=7, verbose_name='Цвет тэга'),
        ),
    ]
