# Generated by Django 6.0 on 2026-01-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_collection_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_stock',
            field=models.JSONField(blank=True, default=dict, verbose_name='Остаток по размерам'),
        ),
    ]
