# Generated by Django 6.0 on 2026-02-11 00:00

from django.db import migrations, models


def forwards_copy_collection(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    through = Product.collections.through
    rows = []
    for product_id, collection_id in Product.objects.exclude(collection__isnull=True).values_list('id', 'collection_id'):
        rows.append(through(product_id=product_id, collection_id=collection_id))
    if rows:
        through.objects.bulk_create(rows, ignore_conflicts=True)


def backwards_restore_collection(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    for product in Product.objects.all():
        first = product.collections.order_by('id').first()
        product.collection_id = first.id if first else None
        product.save(update_fields=['collection'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_product_size_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='products_m2m', to='catalog.collection'),
        ),
        migrations.RunPython(forwards_copy_collection, backwards_restore_collection),
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.AlterField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.collection'),
        ),
    ]
