# Generated by Django 6.0 on 2025-12-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonuses_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Использовано бонусов'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Итого к оплате'),
        ),
    ]
