# Generated by Django 6.0 on 2025-12-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_bonuses_used_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('waiting_payment', 'Ожидание оплаты'), ('purchased', 'Покупка (Оплачено)'), ('cancelled', 'Отмена'), ('sent', 'Отправлен в WhatsApp')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
